exec: [ "service" , "nginx" , "start" ]

data_sources:
  - file
  - defaults
  - environment
  - environment_json

template_sources:
  - file

defaults:
  nginx.conf.erb:
    env_servers: {
      host: 'backend',
      port: '3000'
    }

environments:
  development:
     nginx.conf.erb:
      target: /etc/nginx/nginx.conf
      config: {}

  staging:
      nginx.conf.erb:
        target: /etc/nginx/nginx.conf
        config: {}

  production:
      nginx.conf.erb:
        target: /etc/nginx/nginx.conf
        config: {}